# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :deploy_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --flavor dev --target lib/main_dev.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_path: "../build/app/outputs/apk/dev/release/app-dev-release.apk",
      android_artifact_type: "APK",
      testers: ENV["FIREBASE_TESTERS"],
      release_notes: "first fastlane release app distribution"
    )
  end
end
