# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :deploy_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:122514249495:android:692598f646b0c85042c952",
      firebase_cli_token: "1//03XhO-H3glHSCCgYIARAAGAMSNwF-L9IrbCgvkgWBQMB2rwlgZtgf8bx27BxHlltZAmQ4gIx7knyyhyEckc9WrnP6K4CowLnY0Ao",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      android_artifact_type: "APK",
      testers: "mohammedemad2001c@gmail.com, yousifkhalid544@gmail.com",
      release_notes: "first fastlane release app distribution"
    )
  end
end
